### ISSUE TITLE
RDF: optimizing data structure to speed up queries

### ISSUE THREAD

**Issue by k00ni** [AKSW/transform-bvl-pages-to-csv-file#7]
Discussion started in https://github.com/AKSW/transform-bvl-csv-to-json-files/issues/6

> Beside the performance another question is, who decides (and where) if an elevator is wheelchair accessible, eg what is the min door width. It think its better to not do that in the building navigator app, but in the data processing.

Do you mean, that you would like to have only a few fields, which tell you if something is e.g. partly/fully wheelchair accessible?

**Comment by simeonackermann** [comment]
Jep, like we had in the building-coordinates.json.

**Comment by k00ni** [comment]
How much is the performance "loss" with these rather complex queries? 

Information when something is wheelchair accessible, for instance, can be found here: https://github.com/AKSW/shacl-shapes/tree/master/shape-groups/accessible-place

**Comment by simeonackermann** [comment]
I dont really know how much the performance loss is. A very first test seems ok.

**Comment by simeonackermann** [comment]
But beside possible performance issues, dont you think the "calculation" when something is full or partly accessible should be handled in the data transformation process?

**Comment by k00ni** [comment]
Sure, just wanted to see, if its urgent or can be delayed. Will look into this next week.

You can assume that there will be fields which indicate if something is for instance partly wheelchair accessible.

**Comment by k00ni** [comment]
I updated the places.n3. Commit message: https://github.com/AKSW/transform-bvl-pages-to-csv-file/commit/16abf6fb1d9436153e80c81cd9e3f0ab4a53d0e1

**Comment by simeonackermann** [comment]
Nice, we can close this issue
