### ISSUE TITLE
Parking slots on front?

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/transform-bvl-pages-to-csv-file#9]
We have the properties 

```
numberOfSlotsDisabledParkingLotInFrontOfPlace
numberOfSlotsDisabledParkingLotOnSite
locationParkingLotOnSite
```

But no property for parking slots on front (for may not disabled people).

Is this missing or not documented?

**Comment by k00ni** [comment]
Not documented, because its not clear when thats the case or not. Sometimes buildings have lots in front, but they are always occupied. That is a problem in areas with high traffic. Therefore no information to not mislead people.

Please close, if this answer solves the issue.

**Comment by simeonackermann** [comment]
Sure, its not always that clear.

Closed because of no information
